/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.trabalhofinal.view;

import com.mycompany.trabalhofinal.Gerenciamento;
import java.text.DecimalFormat;

/**
 *
 * @author Usuario
 */
public class DialogExtrato extends javax.swing.JDialog {
//Gerenciamento gerenciamento = new Gerenciamento();

    /**
     * Creates new form DialogExtrato
     *
     * @param parent
     * @param modal
     * @param gerenciamento
     */
    public DialogExtrato(java.awt.Frame parent, boolean modal, Gerenciamento gerenciamento) {
        super(parent, modal);
        initComponents();
        setTitle("Extrato Financeiro");
        jTxtExtrato.setEditable(false);

        DecimalFormat df = new DecimalFormat("#,##0.00");

        double receitas = gerenciamento.calcularTotalReceitas();
        double despesas = gerenciamento.calcularTotalDespesas();
        double saldoAtual = gerenciamento.calcularSaldoAtual();
        double saldoTotal = gerenciamento.calcularSaldoTotal();

        String extrato = "Receitas: R$ " + df.format(receitas) + "\n"
                + "Despesas: R$ " + df.format(despesas) + "\n"
                + "Saldo Atual: R$ " + df.format(saldoAtual) + "\n"
                + "Saldo Total: R$ " + df.format(saldoTotal) + "\n";

        jTxtExtrato.setText(extrato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtExtrato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtExtrato.setColumns(20);
        jTxtExtrato.setRows(5);
        jScrollPane1.setViewportView(jTxtExtrato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtExtrato;
    // End of variables declaration//GEN-END:variables
}
