/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.trabalhofinal.view;

import com.mycompany.trabalhofinal.Despesas;
import com.mycompany.trabalhofinal.Lancamento;
import com.mycompany.trabalhofinal.Receita;
import java.awt.Frame;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class DialogLancamento extends javax.swing.JDialog {

    /**
     * Creates new form Dialog
     *
     * @param parent
     * @param modal
     * @param lista
     */
    public DialogLancamento(Frame parent, boolean modal, ArrayList<Lancamento> lista) {
        super(parent, modal);
        initComponents();
        setTitle("Lançamentos");
        DecimalFormat df = new DecimalFormat("#,##0.00"); // formato com 2 casas decimais

        String texto = "";
        for (int i = 0; i < lista.size(); i++) {
            Lancamento l = lista.get(i);
            String tipo = "Despesa";
            String categoria = "";

            if (l instanceof Receita) {
                tipo = "Receita";
                categoria = ((Receita) l).getCategoriaR().name();
            } else if (l instanceof Despesas) {
                categoria = ((Despesas) l).getCategoriaD().name();
            }

            String valorFormatado = df.format(l.getValor());

            texto += "Data: " + l.getData() + " | Valor: R$ " + valorFormatado
                    + " | Categoria: " + categoria + " | Tipo: " + tipo + "\n";
        }

        jTxtArea.setText(texto);
        jTxtArea.setCaretPosition(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtArea.setColumns(20);
        jTxtArea.setRows(5);
        jScrollPane1.setViewportView(jTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtArea;
    // End of variables declaration//GEN-END:variables
}
